'solution'
mate-academy/py-tickets-and-orders pull request #330
Opened 2023-05-12 18:36 UTC by IvanGuculyak

2023-05-12 18:53 UTC, Vasyl-Smutok requested changes

2023-05-12 18:53 UTC, Vasyl-Smutok commented on services/user.py
> +    new_user.save()
DRY

here and in 42-48 lines

2023-05-12 18:53 UTC, Vasyl-Smutok commented on db/models.py
> +               f"(row: {self.row}, seat: {self.seat})"
better use `()` then `\`

2023-05-13 09:24 UTC, ArsenPidhoretskyi requested changes

2023-05-13 09:24 UTC, ArsenPidhoretskyi commented on services/movie.py
> +    title: str = None
It accepts Optional[str] because None as default. Change in all places(just your code)

2023-05-13 09:24 UTC, ArsenPidhoretskyi commented on services/movie_session.py
> +        })
Use list comprehension

2023-05-13 09:24 UTC, ArsenPidhoretskyi commented on services/order.py
> +        return Order.objects.filter(user_id=user.id)
You can use related import:
user__username

2023-05-13 09:24 UTC, ArsenPidhoretskyi commented on services/user.py
> +        new_user.last_name = last_name
You can move it to new function and remove duplicate of code inside update_user and create_user

2023-05-13 11:29 UTC, Vasyl-Smutok approved these changes
Good Job 👍

2024-05-22 11:52 UTC, closed without merging